language: python
dist: trusty
python:
  - "3.3"
  - "3.4"
  - "3.5"
addons:
  postgresql: "9.5"
before_install:
  - psql --version
# command to install dependencies
install: "pip install -r requirements.txt"
before_script:

  - psql -c 'create database "test-db";' -U postgres
  - psql -c 'create database "reddit-db";' -U postgres
  - psql -c "CREATE USER craw WITH PASSWORD 'craw';" -U postgres
# command to run tests
script: sed -i.bak 's/^\(env =\).*/\1 test/' config.cfg | python manage.py test 
