# Install python3, pip and requirments
---
- hosts: local
  tasks:
  - name: Install python3
    apt: name=python3-setuptools state=installed
    become: true
  - name: Install virtualenv
    pip: name=virtualenv
    become: true
  - name: Install psycong
    pip: name=psycopg2
    become: true
  - easy_install: name=pip state=latest executable=easy_install-3.3
    become: true
