# Install python3, pip and requirments
---
- hosts: local
  tasks:
  - name: Install python3
    apt: name=python3-pip state=installed
    become: true
  - name: Install setuptools
    pip: name=setuptools
    become: true
  - name: Install setuptools
    pip: name=virtualenv
    become: true
  - name: Install virtualenv
    apt: name=python-virtualenv
    become: true
  - easy_install: name=pip state=latest executable=easy_install-3.3
    become: true
